server:
  port: 8000
  servlet.context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmunews?characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: "0320"
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  web:
    resources:
        static-locations: classpath:/static/,classpath:/templates/
mybatis:
  mapper-locations: classpath:*.xml
  type-aliases-package: cn.heroisuseless.back.entity
  configuration:
    map-underscore-to-camel-case: true


